using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BrickSchema.Net.Classes.Equipments.HVACType.TerminalUnits
{
    public class RadiantPanel : TerminalUnit
    {

        new public static string About
        {
            get
            {
                return "A radiant panel is a type of heating or cooling system that provides temperature control by emitting radiant energy. Radiant panels can be used for heating (most common) or cooling, and they work on the principle of electromagnetic radiation. This is a fundamental difference from most common heating or cooling systems that work primarily on the principle of convection, where air is heated or cooled and then circulated around the room." +
                    "\r\n\r\nRadiant panels are often embedded into a surface, like the floor, wall, or ceiling, where they transfer energy directly to the objects and people in the room. The emitted radiant energy is absorbed by the objects in the room, heating them up or cooling them down, which in turn raises or lowers the temperature of the room." +
                    "\r\n\r\nThe types of radiant panels include:" +
                    "\r\n\r\n1. **Electric Radiant Panels:** These panels use electrical resistance to generate heat. They can be mounted on walls, ceilings, or floors, and they are usually made from a conductive material like aluminum for efficient heat transfer." +
                    "\r\n\r\n2. **Hydronic Radiant Panels:** These panels circulate hot or chilled water through pipes embedded in the panel. The pipes can be embedded in a variety of surfaces, including walls, floors, and ceilings, but floor installations are most common. This type of system is often more efficient for heating larger spaces than electric radiant panels." +
                    "\r\n\r\nRadiant panels can be very energy efficient, particularly in situations where it's important to maintain a consistent, comfortable temperature over a long period. They also avoid some of the common issues associated with forced-air systems, like drafts and uneven heating or cooling." +
                    "\r\n\r\nHowever, radiant panels can be expensive to install, especially in existing structures, because they often require substantial modification of the building's structure. Additionally, because radiant panels heat objects rather than the air, they can take longer to change the temperature in a room compared to forced-air systems." +
                    "\r\n\r\nRadiant panels also require careful design and installation to ensure that they are safe and effective. For example, the materials used in the panel, as well as the structure in which the panel is embedded, must be able to safely withstand the heat generated by the system. Similarly, the layout of the panels must be carefully planned to provide even heating or cooling." +
                    "\r\n\r\nOverall, radiant panels can be an effective and efficient option for heating or cooling, particularly in buildings where maintaining a consistent, comfortable temperature is important. However, they require careful planning and design, and they may not be suitable for all applications.";
            }
        }

    }


}
